port: /dev/ttyUSB0
#port: /dev/rfcomm0
baud: 57600
timeout: 0.05
rate: 20
wheel_diameter: 0.127
wheel_track: 0.325
encoder_resolution: 624
gear_reduction: 1.667
units: 0
VPID_P: 2
VPID_I: 0
VPID_D: 5
VPID_L: 45
DPID_P: 1
DPID_I: 0
DPID_D: 0
DPID_A: 5
DPID_B: 5

publish_sensors: True

sensors: {
    'analog': { 'voltage': {'pin': 5, 'type': 'Voltage'}, 'head_ir': {'pin': 4, 'type': 'GP2D12'}, 'drive_current': {'pin': 1, 'type': 'PhidgetsCurrent'} },
    'digital': {'head_sonar': {'pin': 4, 'type': 'Ping'} }
}