port: /dev/ttyUSB0
#port: /dev/rfcomm0
baud: 57600
timeout: 0.5
sensor_rate: 30
base_controller_rate: 10
wheel_diameter: 0.132
wheel_track: 0.3365
encoder_resolution: 624
gear_reduction: 1.667
units: 0
VPID_P: 2
VPID_I: 0
VPID_D: 5
VPID_L: 45
DPID_P: 1
DPID_I: 0
DPID_D: 0
DPID_A: 5
DPID_B: 5

publish_sensors: False

#'analog': { 'voltage': {'pin': 5, 'type': 'Voltage'}, 'head_ir': {'pin': 4, 'type': 'GP2D12'}, 'drive_current': {'pin': 1, 'type': 'PhidgetsCurrent'} },

sensors: {
    'digital': {'base_sonar': {'pin': 5, 'type': 'Ping'} }
}