<?xml version="1.0"?>
<robot
    xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
    xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
    xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface">

    <!-- Included URDF Files -->
    <include filename="$(find turtlebot_urdf)/urdf/materials.urdf.xacro" />
    <!--
    <include filename="$(find turtlebot_urdf)/urdf/turtlebot_wheel.xacro" />
    -->

    <!-- Properties (Constants) -->
    <property name="M_PI" value="3.14159"/>
    
    <property name="base_size_x" value="0.33" />
    <property name="base_size_y" value="0.33" />
    <property name="base_calibration_factor" value="0.5" />
    
    <macro name="turtlebot">
        <!-- base_footprint is a fictitious link(frame) that is on the ground right below base_link origin,
             navigation stack depends on this frame -->
        <link name="base_footprint">
            <inertial>
                <mass value="0.0001" />
                <origin xyz="0 0 0" />
                <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
                         iyy="0.0001" iyz="0.0" 
                         izz="0.0001" />
            </inertial>

            <visual>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <box size="0.001 0.001 0.001" />
                </geometry>
                <material name="Green" />
            </visual>

            <collision>
                <origin xyz="0 0 0.017" rpy="0 0 0" />
                <geometry>
                  <box size="0.001 0.001 0.001" />
                </geometry>
            </collision>
        </link>

        <joint name="base_footprint_joint" type="fixed">
            <!-- NB: While you would think this would make it go up, it is oddly reversed.
                 This moves the joint to 0,0,0 where we want it for rviz, etc. -->
            <origin xyz="0 0 0.017" rpy="0 0 0" />        
            <parent link="base_footprint"/>
            <child link="base_link" />
        </joint>

        <!-- Links and Joints (i.e., the robot) -->
        <link name="base_link">
            <inertial>
                <mass value="12" />
                <origin xyz="${-base_size_x/2} 0 0.017" />
                <inertia ixx="1.0" ixy="0.0" ixz="0.0"
                         iyy="1.0" iyz="0.0" 
                         izz="1.0" />
            </inertial>
            
            <visual>
                <origin xyz="0.0 0.0 0.02" rpy="0 0 0" />
                <geometry>
                    <mesh filename="package://turtlebot_urdf/meshes/create_body.dae"/>
                </geometry>
                <material name="Blue" />
            </visual>
            
            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
                <geometry>
                    <mesh filename="package://turtlebot_urdf/meshes/create_body.stl"/>
                </geometry>
            </collision>
        </link>

        <joint name="imu_joint" type="fixed">
            <!-- NB: While you would think this would make it go up, it is oddly reversed.
                 This moves the joint to 0,0,0 where we want it for rviz, etc. -->
            <origin xyz="0 0 0.03" rpy="0 0 0" />        
            <parent link="base_link"/>
            <child link="gyro_link" />
        </joint>

        <link name="gyro_link">
            <inertial>
                <mass value="0.01" />
                <origin xyz="0 0 0.03" />
                <inertia ixx="1.0" ixy="0.0" ixz="0.0"
                         iyy="1.0" iyz="0.0" 
                         izz="1.0" />
            </inertial>
            
            <visual>
                <origin xyz="0.0 0.0 0.02" rpy="0 0 0" />
                <geometry>
                  <cylinder radius="0.002" length="0.006" />
                </geometry>
                <material name="Blue" />
            </visual>
            
        </link>


        <joint name="base_layer1_joint" type="fixed">
          <origin xyz="0 0 0.064" rpy="0 0 0" />
          <parent link="base_link" />
          <child link="base_layer1_link" />
        </joint>

        <link name="base_layer1_link">
          <visual>
            <geometry>
              <cylinder radius="0.165" length="0.006" />
            </geometry>
            <material name="White" />
          </visual>
          <inertial>
              <mass value="0.0001" />
              <origin xyz="0 0 0" />
              <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
                       iyy="0.0001" iyz="0.0" 
                       izz="0.0001" />
          </inertial>
        </link>

        <joint name="base_layer2_joint" type="fixed">
          <origin xyz="0 0 0.0254" rpy="0 0 0" />
          <parent link="base_layer1_link" />
          <child link="base_layer2_link" />
        </joint>

        <link name="base_layer2_link">
          <visual>
            <geometry>
              <cylinder radius="0.165" length="0.006" />
            </geometry>
            <material name="White" />
          </visual>
          <inertial>
              <mass value="0.0001" />
              <origin xyz="0 0 0" />
              <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
                       iyy="0.0001" iyz="0.0" 
                       izz="0.0001" />
          </inertial>
        </link>

        <joint name="base_layer3_joint" type="fixed">
          <origin xyz="0 0 0.0508" rpy="0 0 0" />
          <parent link="base_layer2_link" />
          <child link="base_layer3_link" />
        </joint>

        <link name="base_layer3_link">
          <visual>
            <geometry>
              <cylinder radius="0.165" length="0.006" />
            </geometry>
            <material name="White" />
          </visual>
          <inertial>
              <mass value="0.0001" />
              <origin xyz="0 0 0" />
              <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
                       iyy="0.0001" iyz="0.0" 
                       izz="0.0001" />
          </inertial>
        </link>

        <joint name="base_kinect_joint" type="fixed">
          <origin xyz="0.065 0 0.06" rpy="0 0 0" />
          <parent link="base_layer3_link" />
          <child link="base_kinect_link" />
        </joint>

        <link name="base_kinect_link">
          <visual>
            <geometry>
              <box size="0.064 0.121 0.0381" />
            </geometry>
            <material name="Blue" />
          </visual>
          <inertial>
              <mass value="0.0001" />
              <origin xyz="0 0 0" />
              <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
                       iyy="0.0001" iyz="0.0" 
                       izz="0.0001" />
          </inertial>
        </link>

        <joint name="base_kinect_depth_joint" type="fixed">
          <origin xyz="0 0.028 0" rpy="0 0 0" />
          <parent link="base_kinect_link" />
          <child link="base_kinect_depth_frame" />
        </joint>

        <link name="base_kinect_depth_frame">
          <inertial>
              <mass value="0.0001" />
              <origin xyz="0 0 0" />
              <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
                       iyy="0.0001" iyz="0.0" 
                       izz="0.0001" />
          </inertial>
        </link>

        <joint name="kinect_depth_optical_joint" type="fixed">
          <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
          <parent link="base_kinect_depth_frame" />
          <child link="base_kinect_depth_optical_frame" />
        </joint>

        <link name="base_kinect_depth_optical_frame">
          <inertial>
              <mass value="0.0001" />
              <origin xyz="0 0 0" />
              <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
                       iyy="0.0001" iyz="0.0" 
                       izz="0.0001" />
          </inertial>
        </link>


        <joint name="base_kinect_rgb_joint" type="fixed">
          <origin xyz="0 -0.005 0" rpy="0 0 0" />
          <parent link="base_kinect_link" />
          <child link="base_kinect_rgb_frame" />
        </joint>

        <link name="base_kinect_rgb_frame">
          <inertial>
              <mass value="0.0001" />
              <origin xyz="0 0 0" />
              <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
                       iyy="0.0001" iyz="0.0" 
                       izz="0.0001" />
          </inertial>
        </link>

        <joint name="kinect_rgb_optical_joint" type="fixed">
          <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
          <parent link="base_kinect_rgb_frame" />
          <child link="base_kinect_rgb_optical_frame" />
        </joint>

        <link name="base_kinect_rgb_optical_frame">
          <inertial>
              <mass value="0.0001" />
              <origin xyz="0 0 0" />
              <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
                       iyy="0.0001" iyz="0.0" 
                       izz="0.0001" />
          </inertial>
        </link>



    </macro>
</robot>
