/* Auto-generated by genmsg_cpp for file /home/patrick/Eclipse/ros/pi-robot-ros-stack/serializer/srv/GetAnalog.srv */
#ifndef SERIALIZER_SERVICE_GETANALOG_H
#define SERIALIZER_SERVICE_GETANALOG_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"

#include "ros/service_traits.h"




namespace serializer
{
template <class ContainerAllocator>
struct GetAnalogRequest_ : public ros::Message
{
  typedef GetAnalogRequest_<ContainerAllocator> Type;

  GetAnalogRequest_()
  : pin(0)
  , cached(false)
  {
  }

  GetAnalogRequest_(const ContainerAllocator& _alloc)
  : pin(0)
  , cached(false)
  {
  }

  typedef uint8_t _pin_type;
  uint8_t pin;

  typedef uint8_t _cached_type;
  uint8_t cached;


private:
  static const char* __s_getDataType_() { return "serializer/GetAnalogRequest"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROSCPP_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "53bed398bc7ef4510938f1f4d6a12a22"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROSCPP_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "4e943b13b25d974978eb5df74257558f"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROSCPP_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "uint8 pin\n\
bool cached\n\
\n\
"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROSCPP_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROSCPP_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, pin);
    ros::serialization::serialize(stream, cached);
    return stream.getData();
  }

  ROSCPP_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, pin);
    ros::serialization::deserialize(stream, cached);
    return stream.getData();
  }

  ROSCPP_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(pin);
    size += ros::serialization::serializationLength(cached);
    return size;
  }

  typedef boost::shared_ptr< ::serializer::GetAnalogRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::serializer::GetAnalogRequest_<ContainerAllocator>  const> ConstPtr;
}; // struct GetAnalogRequest
typedef  ::serializer::GetAnalogRequest_<std::allocator<void> > GetAnalogRequest;

typedef boost::shared_ptr< ::serializer::GetAnalogRequest> GetAnalogRequestPtr;
typedef boost::shared_ptr< ::serializer::GetAnalogRequest const> GetAnalogRequestConstPtr;


template <class ContainerAllocator>
struct GetAnalogResponse_ : public ros::Message
{
  typedef GetAnalogResponse_<ContainerAllocator> Type;

  GetAnalogResponse_()
  : value(0)
  {
  }

  GetAnalogResponse_(const ContainerAllocator& _alloc)
  : value(0)
  {
  }

  typedef uint8_t _value_type;
  uint8_t value;


private:
  static const char* __s_getDataType_() { return "serializer/GetAnalogResponse"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROSCPP_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "e4da51e86d3bac963ee2bb1f41031407"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROSCPP_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "4e943b13b25d974978eb5df74257558f"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROSCPP_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "uint8 value\n\
\n\
\n\
"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROSCPP_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROSCPP_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, value);
    return stream.getData();
  }

  ROSCPP_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, value);
    return stream.getData();
  }

  ROSCPP_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(value);
    return size;
  }

  typedef boost::shared_ptr< ::serializer::GetAnalogResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::serializer::GetAnalogResponse_<ContainerAllocator>  const> ConstPtr;
}; // struct GetAnalogResponse
typedef  ::serializer::GetAnalogResponse_<std::allocator<void> > GetAnalogResponse;

typedef boost::shared_ptr< ::serializer::GetAnalogResponse> GetAnalogResponsePtr;
typedef boost::shared_ptr< ::serializer::GetAnalogResponse const> GetAnalogResponseConstPtr;

struct GetAnalog
{

typedef GetAnalogRequest Request;
typedef GetAnalogResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct GetAnalog
} // namespace serializer

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::serializer::GetAnalogRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "53bed398bc7ef4510938f1f4d6a12a22";
  }

  static const char* value(const  ::serializer::GetAnalogRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x53bed398bc7ef451ULL;
  static const uint64_t static_value2 = 0x0938f1f4d6a12a22ULL;
};

template<class ContainerAllocator>
struct DataType< ::serializer::GetAnalogRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "serializer/GetAnalogRequest";
  }

  static const char* value(const  ::serializer::GetAnalogRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::serializer::GetAnalogRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "uint8 pin\n\
bool cached\n\
\n\
";
  }

  static const char* value(const  ::serializer::GetAnalogRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::serializer::GetAnalogRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::serializer::GetAnalogResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "e4da51e86d3bac963ee2bb1f41031407";
  }

  static const char* value(const  ::serializer::GetAnalogResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xe4da51e86d3bac96ULL;
  static const uint64_t static_value2 = 0x3ee2bb1f41031407ULL;
};

template<class ContainerAllocator>
struct DataType< ::serializer::GetAnalogResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "serializer/GetAnalogResponse";
  }

  static const char* value(const  ::serializer::GetAnalogResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::serializer::GetAnalogResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "uint8 value\n\
\n\
\n\
";
  }

  static const char* value(const  ::serializer::GetAnalogResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::serializer::GetAnalogResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::serializer::GetAnalogRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.pin);
    stream.next(m.cached);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct GetAnalogRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::serializer::GetAnalogResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.value);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct GetAnalogResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<serializer::GetAnalog> {
  static const char* value() 
  {
    return "4e943b13b25d974978eb5df74257558f";
  }

  static const char* value(const serializer::GetAnalog&) { return value(); } 
};

template<>
struct DataType<serializer::GetAnalog> {
  static const char* value() 
  {
    return "serializer/GetAnalog";
  }

  static const char* value(const serializer::GetAnalog&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<serializer::GetAnalogRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "4e943b13b25d974978eb5df74257558f";
  }

  static const char* value(const serializer::GetAnalogRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<serializer::GetAnalogRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "serializer/GetAnalog";
  }

  static const char* value(const serializer::GetAnalogRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<serializer::GetAnalogResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "4e943b13b25d974978eb5df74257558f";
  }

  static const char* value(const serializer::GetAnalogResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<serializer::GetAnalogResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "serializer/GetAnalog";
  }

  static const char* value(const serializer::GetAnalogResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // SERIALIZER_SERVICE_GETANALOG_H

