/* Auto-generated by genmsg_cpp for file /home/patrick/Eclipse/serializer-ros-pkg/serializer/srv/SetServo.srv */
#ifndef SERIALIZER_SERVICE_SETSERVO_H
#define SERIALIZER_SERVICE_SETSERVO_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"

#include "ros/service_traits.h"




namespace serializer
{
template <class ContainerAllocator>
struct SetServoRequest_ : public ros::Message
{
  typedef SetServoRequest_<ContainerAllocator> Type;

  SetServoRequest_()
  : id(0)
  , value(0)
  {
  }

  SetServoRequest_(const ContainerAllocator& _alloc)
  : id(0)
  , value(0)
  {
  }

  typedef uint8_t _id_type;
  uint8_t id;

  typedef int8_t _value_type;
  int8_t value;


private:
  static const char* __s_getDataType_() { return "serializer/SetServoRequest"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROSCPP_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "72b7969bdddd9940a4e63f5c59126060"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROSCPP_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "72b7969bdddd9940a4e63f5c59126060"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROSCPP_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "uint8 id\n\
int8 value\n\
\n\
"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROSCPP_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROSCPP_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, id);
    ros::serialization::serialize(stream, value);
    return stream.getData();
  }

  ROSCPP_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, id);
    ros::serialization::deserialize(stream, value);
    return stream.getData();
  }

  ROSCPP_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(id);
    size += ros::serialization::serializationLength(value);
    return size;
  }

  typedef boost::shared_ptr< ::serializer::SetServoRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::serializer::SetServoRequest_<ContainerAllocator>  const> ConstPtr;
}; // struct SetServoRequest
typedef  ::serializer::SetServoRequest_<std::allocator<void> > SetServoRequest;

typedef boost::shared_ptr< ::serializer::SetServoRequest> SetServoRequestPtr;
typedef boost::shared_ptr< ::serializer::SetServoRequest const> SetServoRequestConstPtr;


template <class ContainerAllocator>
struct SetServoResponse_ : public ros::Message
{
  typedef SetServoResponse_<ContainerAllocator> Type;

  SetServoResponse_()
  {
  }

  SetServoResponse_(const ContainerAllocator& _alloc)
  {
  }


private:
  static const char* __s_getDataType_() { return "serializer/SetServoResponse"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROSCPP_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "d41d8cd98f00b204e9800998ecf8427e"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROSCPP_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "72b7969bdddd9940a4e63f5c59126060"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROSCPP_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "\n\
\n\
\n\
"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROSCPP_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROSCPP_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    return stream.getData();
  }

  ROSCPP_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    return stream.getData();
  }

  ROSCPP_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    return size;
  }

  typedef boost::shared_ptr< ::serializer::SetServoResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::serializer::SetServoResponse_<ContainerAllocator>  const> ConstPtr;
}; // struct SetServoResponse
typedef  ::serializer::SetServoResponse_<std::allocator<void> > SetServoResponse;

typedef boost::shared_ptr< ::serializer::SetServoResponse> SetServoResponsePtr;
typedef boost::shared_ptr< ::serializer::SetServoResponse const> SetServoResponseConstPtr;

struct SetServo
{

typedef SetServoRequest Request;
typedef SetServoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct SetServo
} // namespace serializer

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::serializer::SetServoRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "72b7969bdddd9940a4e63f5c59126060";
  }

  static const char* value(const  ::serializer::SetServoRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x72b7969bdddd9940ULL;
  static const uint64_t static_value2 = 0xa4e63f5c59126060ULL;
};

template<class ContainerAllocator>
struct DataType< ::serializer::SetServoRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "serializer/SetServoRequest";
  }

  static const char* value(const  ::serializer::SetServoRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::serializer::SetServoRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "uint8 id\n\
int8 value\n\
\n\
";
  }

  static const char* value(const  ::serializer::SetServoRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::serializer::SetServoRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::serializer::SetServoResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::serializer::SetServoResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::serializer::SetServoResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "serializer/SetServoResponse";
  }

  static const char* value(const  ::serializer::SetServoResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::serializer::SetServoResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
\n\
\n\
";
  }

  static const char* value(const  ::serializer::SetServoResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::serializer::SetServoResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::serializer::SetServoRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.id);
    stream.next(m.value);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct SetServoRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::serializer::SetServoResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct SetServoResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<serializer::SetServo> {
  static const char* value() 
  {
    return "72b7969bdddd9940a4e63f5c59126060";
  }

  static const char* value(const serializer::SetServo&) { return value(); } 
};

template<>
struct DataType<serializer::SetServo> {
  static const char* value() 
  {
    return "serializer/SetServo";
  }

  static const char* value(const serializer::SetServo&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<serializer::SetServoRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "72b7969bdddd9940a4e63f5c59126060";
  }

  static const char* value(const serializer::SetServoRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<serializer::SetServoRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "serializer/SetServo";
  }

  static const char* value(const serializer::SetServoRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<serializer::SetServoResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "72b7969bdddd9940a4e63f5c59126060";
  }

  static const char* value(const serializer::SetServoResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<serializer::SetServoResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "serializer/SetServo";
  }

  static const char* value(const serializer::SetServoResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // SERIALIZER_SERVICE_SETSERVO_H

