/* Auto-generated by genmsg_cpp for file /home/patrick/Eclipse/serializer-ros-pkg/serializer/srv/TravelDistance.srv */
#ifndef SERIALIZER_SERVICE_TRAVELDISTANCE_H
#define SERIALIZER_SERVICE_TRAVELDISTANCE_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"

#include "ros/service_traits.h"




namespace serializer
{
template <class ContainerAllocator>
struct TravelDistanceRequest_ : public ros::Message
{
  typedef TravelDistanceRequest_<ContainerAllocator> Type;

  TravelDistanceRequest_()
  : distance(0.0)
  , velocity(0.0)
  {
  }

  TravelDistanceRequest_(const ContainerAllocator& _alloc)
  : distance(0.0)
  , velocity(0.0)
  {
  }

  typedef double _distance_type;
  double distance;

  typedef double _velocity_type;
  double velocity;


private:
  static const char* __s_getDataType_() { return "serializer/TravelDistanceRequest"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROSCPP_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "938fc8800cae9ac2a395d3178819b617"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROSCPP_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "938fc8800cae9ac2a395d3178819b617"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROSCPP_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "float64 distance\n\
float64 velocity\n\
\n\
"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROSCPP_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROSCPP_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, distance);
    ros::serialization::serialize(stream, velocity);
    return stream.getData();
  }

  ROSCPP_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, distance);
    ros::serialization::deserialize(stream, velocity);
    return stream.getData();
  }

  ROSCPP_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(distance);
    size += ros::serialization::serializationLength(velocity);
    return size;
  }

  typedef boost::shared_ptr< ::serializer::TravelDistanceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::serializer::TravelDistanceRequest_<ContainerAllocator>  const> ConstPtr;
}; // struct TravelDistanceRequest
typedef  ::serializer::TravelDistanceRequest_<std::allocator<void> > TravelDistanceRequest;

typedef boost::shared_ptr< ::serializer::TravelDistanceRequest> TravelDistanceRequestPtr;
typedef boost::shared_ptr< ::serializer::TravelDistanceRequest const> TravelDistanceRequestConstPtr;


template <class ContainerAllocator>
struct TravelDistanceResponse_ : public ros::Message
{
  typedef TravelDistanceResponse_<ContainerAllocator> Type;

  TravelDistanceResponse_()
  {
  }

  TravelDistanceResponse_(const ContainerAllocator& _alloc)
  {
  }


private:
  static const char* __s_getDataType_() { return "serializer/TravelDistanceResponse"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROSCPP_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "d41d8cd98f00b204e9800998ecf8427e"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROSCPP_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "938fc8800cae9ac2a395d3178819b617"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROSCPP_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "\n\
\n\
\n\
"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROSCPP_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROSCPP_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    return stream.getData();
  }

  ROSCPP_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    return stream.getData();
  }

  ROSCPP_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    return size;
  }

  typedef boost::shared_ptr< ::serializer::TravelDistanceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::serializer::TravelDistanceResponse_<ContainerAllocator>  const> ConstPtr;
}; // struct TravelDistanceResponse
typedef  ::serializer::TravelDistanceResponse_<std::allocator<void> > TravelDistanceResponse;

typedef boost::shared_ptr< ::serializer::TravelDistanceResponse> TravelDistanceResponsePtr;
typedef boost::shared_ptr< ::serializer::TravelDistanceResponse const> TravelDistanceResponseConstPtr;

struct TravelDistance
{

typedef TravelDistanceRequest Request;
typedef TravelDistanceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct TravelDistance
} // namespace serializer

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::serializer::TravelDistanceRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "938fc8800cae9ac2a395d3178819b617";
  }

  static const char* value(const  ::serializer::TravelDistanceRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x938fc8800cae9ac2ULL;
  static const uint64_t static_value2 = 0xa395d3178819b617ULL;
};

template<class ContainerAllocator>
struct DataType< ::serializer::TravelDistanceRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "serializer/TravelDistanceRequest";
  }

  static const char* value(const  ::serializer::TravelDistanceRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::serializer::TravelDistanceRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float64 distance\n\
float64 velocity\n\
\n\
";
  }

  static const char* value(const  ::serializer::TravelDistanceRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::serializer::TravelDistanceRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::serializer::TravelDistanceResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::serializer::TravelDistanceResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::serializer::TravelDistanceResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "serializer/TravelDistanceResponse";
  }

  static const char* value(const  ::serializer::TravelDistanceResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::serializer::TravelDistanceResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
\n\
\n\
";
  }

  static const char* value(const  ::serializer::TravelDistanceResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::serializer::TravelDistanceResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::serializer::TravelDistanceRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.distance);
    stream.next(m.velocity);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct TravelDistanceRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::serializer::TravelDistanceResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct TravelDistanceResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<serializer::TravelDistance> {
  static const char* value() 
  {
    return "938fc8800cae9ac2a395d3178819b617";
  }

  static const char* value(const serializer::TravelDistance&) { return value(); } 
};

template<>
struct DataType<serializer::TravelDistance> {
  static const char* value() 
  {
    return "serializer/TravelDistance";
  }

  static const char* value(const serializer::TravelDistance&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<serializer::TravelDistanceRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "938fc8800cae9ac2a395d3178819b617";
  }

  static const char* value(const serializer::TravelDistanceRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<serializer::TravelDistanceRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "serializer/TravelDistance";
  }

  static const char* value(const serializer::TravelDistanceRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<serializer::TravelDistanceResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "938fc8800cae9ac2a395d3178819b617";
  }

  static const char* value(const serializer::TravelDistanceResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<serializer::TravelDistanceResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "serializer/TravelDistance";
  }

  static const char* value(const serializer::TravelDistanceResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // SERIALIZER_SERVICE_TRAVELDISTANCE_H

