/* Auto-generated by genmsg_cpp for file /home/patrick/Eclipse/ros/pi-robot-ros-stack/serializer/srv/Voltage.srv */
#ifndef SERIALIZER_SERVICE_VOLTAGE_H
#define SERIALIZER_SERVICE_VOLTAGE_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"

#include "ros/service_traits.h"




namespace serializer
{
template <class ContainerAllocator>
struct VoltageRequest_ : public ros::Message
{
  typedef VoltageRequest_<ContainerAllocator> Type;

  VoltageRequest_()
  : cached(false)
  {
  }

  VoltageRequest_(const ContainerAllocator& _alloc)
  : cached(false)
  {
  }

  typedef uint8_t _cached_type;
  uint8_t cached;


private:
  static const char* __s_getDataType_() { return "serializer/VoltageRequest"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROSCPP_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "f74dc286356b4ceb85e562e2936e1aea"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROSCPP_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "e83d0a14c1ccae2cbe9da2c6c6a2148f"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROSCPP_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "bool cached\n\
\n\
"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROSCPP_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROSCPP_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, cached);
    return stream.getData();
  }

  ROSCPP_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, cached);
    return stream.getData();
  }

  ROSCPP_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(cached);
    return size;
  }

  typedef boost::shared_ptr< ::serializer::VoltageRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::serializer::VoltageRequest_<ContainerAllocator>  const> ConstPtr;
}; // struct VoltageRequest
typedef  ::serializer::VoltageRequest_<std::allocator<void> > VoltageRequest;

typedef boost::shared_ptr< ::serializer::VoltageRequest> VoltageRequestPtr;
typedef boost::shared_ptr< ::serializer::VoltageRequest const> VoltageRequestConstPtr;


template <class ContainerAllocator>
struct VoltageResponse_ : public ros::Message
{
  typedef VoltageResponse_<ContainerAllocator> Type;

  VoltageResponse_()
  : value(0.0)
  {
  }

  VoltageResponse_(const ContainerAllocator& _alloc)
  : value(0.0)
  {
  }

  typedef double _value_type;
  double value;


private:
  static const char* __s_getDataType_() { return "serializer/VoltageResponse"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROSCPP_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "1b1594d2b74931ef8fe7be8e2d594455"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROSCPP_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "e83d0a14c1ccae2cbe9da2c6c6a2148f"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROSCPP_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "float64 value\n\
\n\
\n\
"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROSCPP_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROSCPP_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, value);
    return stream.getData();
  }

  ROSCPP_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, value);
    return stream.getData();
  }

  ROSCPP_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(value);
    return size;
  }

  typedef boost::shared_ptr< ::serializer::VoltageResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::serializer::VoltageResponse_<ContainerAllocator>  const> ConstPtr;
}; // struct VoltageResponse
typedef  ::serializer::VoltageResponse_<std::allocator<void> > VoltageResponse;

typedef boost::shared_ptr< ::serializer::VoltageResponse> VoltageResponsePtr;
typedef boost::shared_ptr< ::serializer::VoltageResponse const> VoltageResponseConstPtr;

struct Voltage
{

typedef VoltageRequest Request;
typedef VoltageResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct Voltage
} // namespace serializer

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::serializer::VoltageRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "f74dc286356b4ceb85e562e2936e1aea";
  }

  static const char* value(const  ::serializer::VoltageRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xf74dc286356b4cebULL;
  static const uint64_t static_value2 = 0x85e562e2936e1aeaULL;
};

template<class ContainerAllocator>
struct DataType< ::serializer::VoltageRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "serializer/VoltageRequest";
  }

  static const char* value(const  ::serializer::VoltageRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::serializer::VoltageRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bool cached\n\
\n\
";
  }

  static const char* value(const  ::serializer::VoltageRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::serializer::VoltageRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::serializer::VoltageResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "1b1594d2b74931ef8fe7be8e2d594455";
  }

  static const char* value(const  ::serializer::VoltageResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x1b1594d2b74931efULL;
  static const uint64_t static_value2 = 0x8fe7be8e2d594455ULL;
};

template<class ContainerAllocator>
struct DataType< ::serializer::VoltageResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "serializer/VoltageResponse";
  }

  static const char* value(const  ::serializer::VoltageResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::serializer::VoltageResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float64 value\n\
\n\
\n\
";
  }

  static const char* value(const  ::serializer::VoltageResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::serializer::VoltageResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::serializer::VoltageRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.cached);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct VoltageRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::serializer::VoltageResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.value);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct VoltageResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<serializer::Voltage> {
  static const char* value() 
  {
    return "e83d0a14c1ccae2cbe9da2c6c6a2148f";
  }

  static const char* value(const serializer::Voltage&) { return value(); } 
};

template<>
struct DataType<serializer::Voltage> {
  static const char* value() 
  {
    return "serializer/Voltage";
  }

  static const char* value(const serializer::Voltage&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<serializer::VoltageRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "e83d0a14c1ccae2cbe9da2c6c6a2148f";
  }

  static const char* value(const serializer::VoltageRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<serializer::VoltageRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "serializer/Voltage";
  }

  static const char* value(const serializer::VoltageRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<serializer::VoltageResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "e83d0a14c1ccae2cbe9da2c6c6a2148f";
  }

  static const char* value(const serializer::VoltageResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<serializer::VoltageResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "serializer/Voltage";
  }

  static const char* value(const serializer::VoltageResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // SERIALIZER_SERVICE_VOLTAGE_H

