/* Auto-generated by genmsg_cpp for file /home/patrick/Eclipse/ros/pi-robot-ros-pkg/pi_sandbox/demo_tracker/srv/SetCommand.srv */
#ifndef DEMO_TRACKER_SERVICE_SETCOMMAND_H
#define DEMO_TRACKER_SERVICE_SETCOMMAND_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"

#include "ros/service_traits.h"




namespace demo_tracker
{
template <class ContainerAllocator>
struct SetCommandRequest_ : public ros::Message
{
  typedef SetCommandRequest_<ContainerAllocator> Type;

  SetCommandRequest_()
  : command()
  {
  }

  SetCommandRequest_(const ContainerAllocator& _alloc)
  : command(_alloc)
  {
  }

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _command_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  command;


private:
  static const char* __s_getDataType_() { return "demo_tracker/SetCommandRequest"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "cba5e21e920a3a2b7b375cb65b64cdea"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "cba5e21e920a3a2b7b375cb65b64cdea"; }
public:
  ROS_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROS_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "string command\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, command);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, command);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(command);
    return size;
  }

  typedef boost::shared_ptr< ::demo_tracker::SetCommandRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::demo_tracker::SetCommandRequest_<ContainerAllocator>  const> ConstPtr;
}; // struct SetCommandRequest
typedef  ::demo_tracker::SetCommandRequest_<std::allocator<void> > SetCommandRequest;

typedef boost::shared_ptr< ::demo_tracker::SetCommandRequest> SetCommandRequestPtr;
typedef boost::shared_ptr< ::demo_tracker::SetCommandRequest const> SetCommandRequestConstPtr;


template <class ContainerAllocator>
struct SetCommandResponse_ : public ros::Message
{
  typedef SetCommandResponse_<ContainerAllocator> Type;

  SetCommandResponse_()
  {
  }

  SetCommandResponse_(const ContainerAllocator& _alloc)
  {
  }


private:
  static const char* __s_getDataType_() { return "demo_tracker/SetCommandResponse"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "d41d8cd98f00b204e9800998ecf8427e"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "cba5e21e920a3a2b7b375cb65b64cdea"; }
public:
  ROS_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROS_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    return size;
  }

  typedef boost::shared_ptr< ::demo_tracker::SetCommandResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::demo_tracker::SetCommandResponse_<ContainerAllocator>  const> ConstPtr;
}; // struct SetCommandResponse
typedef  ::demo_tracker::SetCommandResponse_<std::allocator<void> > SetCommandResponse;

typedef boost::shared_ptr< ::demo_tracker::SetCommandResponse> SetCommandResponsePtr;
typedef boost::shared_ptr< ::demo_tracker::SetCommandResponse const> SetCommandResponseConstPtr;

struct SetCommand
{

typedef SetCommandRequest Request;
typedef SetCommandResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct SetCommand
} // namespace demo_tracker

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::demo_tracker::SetCommandRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "cba5e21e920a3a2b7b375cb65b64cdea";
  }

  static const char* value(const  ::demo_tracker::SetCommandRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xcba5e21e920a3a2bULL;
  static const uint64_t static_value2 = 0x7b375cb65b64cdeaULL;
};

template<class ContainerAllocator>
struct DataType< ::demo_tracker::SetCommandRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "demo_tracker/SetCommandRequest";
  }

  static const char* value(const  ::demo_tracker::SetCommandRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::demo_tracker::SetCommandRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "string command\n\
\n\
";
  }

  static const char* value(const  ::demo_tracker::SetCommandRequest_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::demo_tracker::SetCommandResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::demo_tracker::SetCommandResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::demo_tracker::SetCommandResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "demo_tracker/SetCommandResponse";
  }

  static const char* value(const  ::demo_tracker::SetCommandResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::demo_tracker::SetCommandResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
\n\
";
  }

  static const char* value(const  ::demo_tracker::SetCommandResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::demo_tracker::SetCommandResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::demo_tracker::SetCommandRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.command);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct SetCommandRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::demo_tracker::SetCommandResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct SetCommandResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<demo_tracker::SetCommand> {
  static const char* value() 
  {
    return "cba5e21e920a3a2b7b375cb65b64cdea";
  }

  static const char* value(const demo_tracker::SetCommand&) { return value(); } 
};

template<>
struct DataType<demo_tracker::SetCommand> {
  static const char* value() 
  {
    return "demo_tracker/SetCommand";
  }

  static const char* value(const demo_tracker::SetCommand&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<demo_tracker::SetCommandRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "cba5e21e920a3a2b7b375cb65b64cdea";
  }

  static const char* value(const demo_tracker::SetCommandRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<demo_tracker::SetCommandRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "demo_tracker/SetCommand";
  }

  static const char* value(const demo_tracker::SetCommandRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<demo_tracker::SetCommandResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "cba5e21e920a3a2b7b375cb65b64cdea";
  }

  static const char* value(const demo_tracker::SetCommandResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<demo_tracker::SetCommandResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "demo_tracker/SetCommand";
  }

  static const char* value(const demo_tracker::SetCommandResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // DEMO_TRACKER_SERVICE_SETCOMMAND_H

